name: Copper Hill

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello from Copper Hill self-hosted Linux runner!
      - name: print system info to verify running on self-hosted runner
        run: uname -a
